### PR TITLE
feat: add foxwallet adapter

### PR DESCRIPTION
**Pull request by ljunb**

### CODE REVIEW

**Comment by zorro11639** [comment]
Thanks a lot for your work. We will merge the PR after reviewing and testing.

**Comment by zorro11639** [comment]
A new adapter can only be released when the according wallet app support Tron Dapps. Does foxwallet support Tron and Tron Dapps ?
If it does support Tron, you can list the wallet in Tron official wallet list first following [this step](https://github.com/web3-geek/tronwallet-adapter/issues/10). 
Thanks a lot!

**Comment by ljunb** [comment]
FoxWallet has supported the Tron network starting from version [5.1.4](https://hc.foxwallet.com/blog/whats-new-in-5-1-4), including TRX, TRC20 transactions, and viewing transaction history, among other features. The support for Tron DApps is ready but has not been released yet. So, does the tronwallet-adapter integration need to wait until the version supporting Tron DApps is released?

**Comment by ljunb** [comment]
Also, I have already sent an email to application@tron.network to request the addition of FoxWallet, but I haven’t received a response yet.

**Comment by zorro11639** [comment]
It's better to publish the adapter after Dapp is supported. If not, the users try to use the adapter may think it's a bug. Also we will do some test work before the publish.

**Comment by ljunb** [comment]
Got it, I will update this comment after the version is released.

**Comment by ljunb** [comment]
Hi, we have added support for Tron DApp interactions, see [FoxWallet 5.3.0 Release Note](https://hc.foxwallet.com/blog/whats-new-in-5-3-0).

**Comment by zorro11639** [comment]
> Hi, we have added support for Tron DApp interactions, see [FoxWallet 5.3.0 Release Note](https://hc.foxwallet.com/blog/whats-new-in-5-3-0).

Thank you, we will test the adapter and release a new version soon.

**Comment by zorro11639** [comment]
> Hi, we have added support for Tron DApp interactions, see [FoxWallet 5.3.0 Release Note](https://hc.foxwallet.com/blog/whats-new-in-5-3-0).

There is no fox wallet.Tronlink.tronWeb:
image

**Comment by ljunb** [comment]
It looks like the tronweb not load successfully from CDN, could you try again please?

**Comment by ljunb** [comment]
Now we use CDN to load `tronweb.js` when injecting the script to WebView, but it seems to fail sometimes. Is there a better way to import it in provider?
```js
export const SETUP_TRONWEB_INSTANCE = (providerState: TronProviderState) => {
  const tronWebScript = CREATE_TRONWEB_INSTANCE(providerState);
  return `(function() {
    // Load TronWeb script from CDN
    var script = document.createElement('script');
    script.type = "text/javascript";
    script.src = 'https://cdn.jsdelivr.net/npm/tronweb@5.3.2/dist/TronWeb.min.js';
    script.onload = function() {
      ${tronWebScript}
    };
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
  true;`;
};
```

**Comment by zorro11639** [comment]
This approach should work fine. When the script is loaded, `TronWeb` will be injected to `window`. But in my foxwallet it failed.

**Comment by ljunb** [comment]
Or try opening it a few more times, is it still failed?

**Comment by ljunb** [comment]
Hello, I’ve found a new method to inject `TronWeb`, and now I can successfully get the instance 100% of the time. You might have to wait for the new version before you can try it out.

**Comment by ljunb** [comment]
Hi, we have released a new version, you can retest the functions of `TronWeb` from our adapter.

**Comment by zorro11639** [comment]
[@tronweb3/tronwallet-adapter-foxwallet](https://www.npmjs.com/package/@tronweb3/tronwallet-adapter-foxwallet?activeTab=readme) is released.

 We have test the Android and IOS app with version 5.3.1 and it works fine.
 There are two points worth noting:
 1. Deeplink works only when user have FoxWallet app installed. If the app is not installed, deeklink won't open the AppStore.
 2. In Android app it can not open website serving by dev server such as `192.168.1.xx`
 
 Thank you for your work. @ljunb

**Pull request merged**
