### PR TITLE
Feat add gatewallet

### PR DESCRIPTION
**Pull request by weixuefeng**

### CODE REVIEW

**Comment by Satan-web3** [comment]
This pr only supports gate app. I want to support gate extension but I find that gate extension doesn't emit accountsChanged event. Do you have any plan to support it? If you do, then when?

**Comment by Satan-web3** [comment]
I found that when I refresh page after connecting to the wallet in the app, the app doesn't reconnect the website automatically. How to fix this problem?

**Comment by Satan-web3** [comment]
And here's another question. When I open the ip address website, the extension doesn't inject gatewallet object into window. Does it meet your expectation?

**Comment by weixuefeng** [comment]
> I found that when I refresh page after connecting to the wallet in the app, the app doesn't reconnect the website automatically. How to fix this problem?

Please add connect cache in your dapp.

**Pull request closed without merging**
