### PR TITLE
feat: add bybit wallet adapter

### PR DESCRIPTION
**Pull request by bybit-web3**

### CODE REVIEW

**Comment by zorro11639** [comment]
Thanks a lot for your work. We will merge the PR after reviewing and testing.

**Comment by zorro11639** [comment]
A new adapter can only be released when the according wallet app support Tron Dapps. Does bybit wallet support Tron and Tron Dapps ?
If it does support Tron, you can list the wallet in Tron official wallet list first following [this step](https://github.com/web3-geek/tronwallet-adapter/issues/10). 
Thanks a lot!

**Comment by zorro11639** [comment]
Thanks for your PR, but we find that bybit wallet does not support Tron and Tron DApp connection currently. Bybit wallet should publish a new version to support Tron network and DApp first, then we can test the function and merge the PR.

**Comment by zorro11639** [comment]
Hello, we have found two issues:
1. Deeplink can only open the bybit app but can not open dapp browser
2. NoPrivateKey Wallet can not use dapp.
3. When bybit app is not installed, the deeplink can not open the AppStore

**Comment by AriesWmj** [comment]
> Hello, we have found two issues:
> 
> 1. Deeplink can only open the bybit app but can not open dapp browser
> 2. NoPrivateKey Wallet can not use dapp.
> 3. When bybit app is not installed, the deeplink can not open the AppStore

for the mpc and cloud wallet, bybit does not support tron chain.

**Comment by zorro11639** [comment]
[@tronweb3/tronwallet-adapter-bybit](https://www.npmjs.com/package/@tronweb3/tronwallet-adapter-bybit) is published. The test version is:
- Android app 4.51.1
- IOS app 4.51.1
- Extension  3.16.3

Thanks for your work.

**Comment by zorro11639** [comment]
Hi, there is an issue with Bybit Extension wallet. Just try the following code (**replace the receiver address with yours**) and the extension popup will display nothing:
```
const wallet = window.bybitWallet.tronLink;
await wallet.request({ method: 'tron_requestAccounts' })
transaction = await wallet.tronWeb.transactionBuilder.sendTrx('replace your address', wallet.tronWeb.toSun(0.1),wallet.tronWeb.defaultAddress.base58);
await wallet.tronWeb.trx.sign(transaction)
```
@bybit-web3

**Pull request merged**
